brokerageManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('transaction.urls')),
    path('admin/', admin.site.urls),
    path('org/', include('organization.urls')),
]

organization/urls.py
from django.urls import path, include

from . import views

app_name = 'organization'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:org_id>', views.org_detail, name='org_detail')
]

transaction/urls.py
from django.urls import path, include

from . import views

app_name = 'transaction'

urlpatterns = [
    path('', views.index, name='index'),
    path('transaction/', views.transaction, name='transaction'),
]

organization/models.py
from django.db import models

# Create your models here.
class Organization(models.Model):
    ORG_TYPE = (
        ('BR', 'broker'),
        ('CL', 'client'),
    )

    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100)
    brokerage_rate = models.DecimalField(max_digits=100, decimal_places=2, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    mobile = models.IntegerField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    org_type = models.CharField(max_length=2, choices=ORG_TYPE, default='CL')
    bank = models.CharField(max_length=100, null=True, blank=True)
    bank_account = models.IntegerField(null=True, blank=True)
    rtgs_code = models.CharField(max_length=100, null=True, blank=True)
    gst_number = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

transaction/models.py
from django.db import models

from organization.models import Organization

# Create your models here.

class Item(models.Model):
     name = models.CharField(max_length=100)

     def __str__(self):
         return self.name

class Transaction(models.Model):
     seller = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name='seller')
     buyer = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name='buyer')
     broker = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name='broker')
     date = models.DateField()
     item = models.ForeignKey(Item, on_delete=models.CASCADE)
     quantity = models.IntegerField()
     weight = models.DecimalField(max_digits=100, decimal_places=2)
     rate = models.IntegerField()
     seller_brokerage_rate = models.DecimalField(max_digits=100, decimal_places=2)
     buyer_brokerage_rate = models.DecimalField(max_digits=100, decimal_places=2)

     def __str__(self):
          return self.seller.name + ' sold to ' + self.buyer.name + ' on ' + str(self.date)

organization/views.py
from django.shortcuts import render

from organization.models import Organization
from transaction.models import Transaction

# Create your views here.
def index(request):
    clients = Organization.objects.filter(org_type='CL').order_by('name')
    context = {
        'clients': clients,
    }
    return render(request, 'organization/index.html', context=context)

def org_detail(request, org_id):
    transactions = Transaction.objects.filter(seller_id=org_id) | Transaction.objects.filter(buyer_id=org_id)
    final_transactions = []

    for transaction in transactions:
        if transaction.seller_id == org_id:
            name, city, brokerage_rate = transaction.buyer, transaction.buyer.city, transaction.seller_brokerage_rate
        else:
            name, city, brokerage_rate = transaction.seller, transaction.seller.city, transaction.buyer_brokerage_rate

        final_transactions.append({
            'name': name,
            'city': city,
            'buyer': transaction.buyer,
            'broker': transaction.broker,
            'date': transaction.date,
            'item': transaction.item,
            'quantity': transaction.quantity,
            'weight': transaction.weight,
            'rate': transaction.rate,
            'brokerage_rate': brokerage_rate,
            'borkerage_amount': brokerage_rate * transaction.weight,
        })

    context = {
        'org_name': Organization.objects.get(pk=org_id).name,
        'transactions': final_transactions,
    }

    return render(request, 'organization/transaction.html', context)

transaction/views.py
from django.shortcuts import render, redirect

from organization.models import Organization
from transaction.models import Transaction, Item

# Create your views here.
def index(request):
    clients = Organization.objects.filter(org_type='CL').order_by('name')
    brokers = Organization.objects.filter(org_type='BR').order_by('name')
    items = Item.objects.all()

    context = {
        'clients': clients,
        'brokers': brokers,
        'items': items,
    }
    return render(request, 'transaction/index.html', context=context)

def transaction(request):
    if request.method == 'POST':
        seller = Organization.objects.get(pk=request.POST['seller'])
        buyer = Organization.objects.get(pk=request.POST['buyer'])
        broker = Organization.objects.get(pk=request.POST['broker'])
        date = request.POST['date']
        item = Item.objects.get(pk=request.POST['item'])
        quantity = request.POST['quantity']
        weight = request.POST['weight']
        rate = request.POST['rate']
        seller_brokerage_rate = seller.brokerage_rate
        buyer_brokerage_rate = buyer.brokerage_rate

        transaction = Transaction(seller=seller, buyer=buyer, broker=broker, date=date, item=item, quantity=quantity, weight=weight, rate=rate,seller_brokerage_rate=seller_brokerage_rate, buyer_brokerage_rate=buyer_brokerage_rate)
        transaction.save()
        return redirect('transaction:index')
    
    return redirect('transaction:index')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %} {% endblock %} </title>
    
    {% block style %}
    {% endblock %}

</head>
<body>
    <a href="/org">Dashboard</a>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/organization/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Brokerage Management {% endblock %}

{% block style %} 
    <link rel="stylesheet" href="{% static 'organization/index.css' %}">
{% endblock %}

{% block content %}
    <ul class="org_list">
        {% for client in clients %}
            <li><a href="{% url 'organization:org_detail' org_id=client.id %}">{{ client.name }}</a></li> 
        {% endfor %}
    </ul>
{% endblock %}

templates/organization/transaction.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Brokerage Management {% endblock %}

{% block style %} 
    <link rel="stylesheet" href="{% static 'organization/index.css' %}">
{% endblock %}

{% block content %}

    <h2>{{ org_name }}</h2>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Name</th>
                <th>City</th>
                <th>Item</th>
                <th>Quantity</th>
                <th>Weight</th>
                <th>Rate</th>
                <th>Brokerage Rate</th>
                <th>Brokerage Amount</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions %}
                <tr>
                    <td>{{transaction.date}}</td>
                    <td>{{transaction.name}}</td>
                    <td>{{transaction.city}}</td>
                    <td>{{transaction.item}}</td>
                    <td>{{transaction.quantity}}</td>
                    <td>{{transaction.weight}}</td>
                    <td>{{transaction.rate}}</td>
                    <td>{{transaction.brokerage_rate}}</td>
                    <td>{{transaction.borkerage_amount  }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/transaction/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Bokerage Management {% endblock %}
{% block style %} 
    <link rel="stylesheet" href="{% static 'transaction/index.css' %}">
{% endblock %}

{% block content %}
    <form action="/transaction/" method="POST" class="form">
        {% csrf_token %}
        {{ form.as_p }}

        <div class="form-field" style="width: 7rem;">
            <label for="date">Date:</label>
            <input type="date" name="date" id="date">
        </div>
        
        <div class="form-section">
            <div class="form-field">
                <label for="seller">Seller:</label>
                <select name="seller" id="seller">
                    {% for client in clients %}
                        <option value="{{ client.id }}">{{ client.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-field">
                <label for="buyer">Buyer:</label>
                <select name="buyer" id="buyer">
                    {% for client in clients %}
                        <option value="{{ client.id }}">{{ client.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

            <div class="form-field">
                <label for="broker">Broker:</label>
                <select name="broker" id="broker">
                    {% for broker in brokers %}
                        <option value="{{ broker.id }}">{{ broker.name }}</option>
                    {% endfor %}
                </select>
            </div>

        <div class="form-section">
            <div class="form-field">
                <label for="item">Item:</label>
                <select name="item" id="item">
                    {% for item in items %}
                        <option value="{{ item.id }}">{{ item.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-field">
                <label for="quantity">Quantity:</label>
                <input type="number" name="quantity" id="quantity" placeholder="Quantity" required>
            </div>

        </div>


        <div class="form-section">
            <div class="form-field">
                <label for="weight">Weight:</label>
                <input type="number" name="weight" id="weight" placeholder="Weight" required>
            </div>

            <div class="form-field">
                <label for="rate">Selling Rate:</label>
                <input type="number" name="rate" id="rate" placeholder="Selling Rate" required>
            </div>
        </div>

        <button type="submit">Submit</button> 
    </form>

   
{% endblock %}